# Site
title:              W x Workshop
bio:                'Technology, Maker, Life.'
description:        "Technology, Maker, Life."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/pic_backgroud.jpg'
#background:         'assets/img/placeholder-big.jpg'
tiled_bg:           true # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
#url:                http://taylantatli.me/Moon
url:                http://wwdd23.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:  woodyworkshop 

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              programmerwudi@gmail.com 
#twitter:            username
#facebook:           username
github:             wwdd23 
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          迪-吴-100476ab 
#xing:              username
instagram:          wudi908
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              wwdd23
#dribbble:          username
#youtube:           username
#soundcloud:        username
weibo:             /u/2137428193
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
