permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 吴迪
  email: programmerwudi@gmail.com
  google_plus: https://plus.google.com/100949260652862828149/posts
  linkedin: https://www.linkedin.com/pub/%E8%BF%AA-%E5%90%B4/ab/476/100
  github: https://github.com/wwdd23

# 站点信息
title: About Me About U
description: 个人笔记 技术分享
url: http://wwdd23.gitblog.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /images/blog-log.jpg
favicon: /images/bike.png

# google analytics 设置
# ???看看是什么
ga:
  id:  
  url: 

# disqus 设置
disqus:
  shortname: wwdd23

# 主题设置，自动激活某个标签
active: 生活

# 首页除了最新文章外显示分类
cates: 
  - Linux
  - bash

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
